version: '3'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass @Sanal89
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master



  web:
    build: .
    container_name: flaskApp
    ports:
      - "5000:5000"

  worker:
    image: web
    command: python app.py run_worker
    depends_on:
      - redis




